### ISSUE TITLE
'inspect' has no attribute 'getargspec'.

### ISSUE THREAD

**Issue by HammadRafique29** [findsimilar/demo#14]
Just run the "py manage.py runserver" command and got this Error. **(Python 3.11)**

![image](https://github.com/findsimilar/demo/assets/112252001/75be592e-651a-41bd-bd13-ab32664c1707)

**Comment by HammadRafique29** [comment]
I think this might be an issue with **pymorphy2** library.

**Comment by quillcraftsman** [comment]
> I think this might be an issue with **pymorphy2** library.

Yes it is. Looks like we need to wait new patch in **pymorphy2**.  Now we just use **python 3.10**. May be there is another options?

**Comment by quillcraftsman** [comment]
I've seen `pymorphy2` GitHub page. Last changes was 3 ears ago. If this library doesn't supports, we can get a problems. 
@HammadRafique29  has already make a pull request there https://github.com/pymorphy2/pymorphy2/pull/167. If it will not been merged we can:
* Find a supported fork
* Fork or copy it ourselves  

This library works with only Russian and Ukrainian languages. @vtyushkevich, pay attention on this issue please

**Comment by HammadRafique29** [comment]
> I've seen `pymorphy2` GitHub page. Last changes was 3 ears ago. If this library doesn't supports, we can get a problems. 
> @HammadRafique29  has already make a pull request there https://github.com/pymorphy2/pymorphy2/pull/167. If it will not been merged we can:
> * Find a supported fork
> * Fork or copy it ourselves  
> 
> This library works with only Russian and Ukrainian languages. @vtyushkevich, pay attention on this issue please

Yes its me who solved this issue. But the problem is that how long will it take to merge my request.

**Comment by quillcraftsman** [comment]
I have open special discussion for this question here: https://github.com/findsimilar/find-similar/discussions/21 in the main repository. Please connect.
